sources:
  - name: NasaNeo
    handler:
      jsonSchema:
        endpoint: https://api.nasa.gov
        operations:
          - type: Query
            field: getNeoFeed
            path: /neo/rest/v1/feed?start_date={args.start_date}&end_date={args.end_date}&api_key={args.api_key}
            method: GET
            responseSchema: ./data/nasa-response.schema.json
            argTypeMap:
              start_date:
                type: string
              end_date:
                type: string
              api_key: 
                type: string

documents:
  - ./src/neo/operations.graphql